name: beer_catalogue_flutter
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-0 <3.0.0"

# Please keep the dependencies sorted alphabetically.
dependencies:
  cached_network_image: ^3.2.1
  dio: ^4.0.6
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.1
  get_it: ^7.2.0
  intl: ^0.17.0
  json_serializable: ^6.2.0
  shared_preferences: ^2.0.11

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  freezed: ^2.0.2

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
